# This is a basic workflow to help you get started with Actions

name: DevX Unpacker Cracked

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Enter CRD code'
        required: true
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Initializing Setup
      run: ./setup2.ps1
    - name: Installing DevX
      run: ./devx.ps1
    - name: Starting CRD 
      run: ${{ github.event.inputs.authcode }} -pin=123456
    - name: Keep Alive
      run: ./timeout.ps1

  
    
