# This is a basic workflow to help you get started with Actions

name: Windows-10

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Enter CRD code'
        required: true
      pincode:
        description: 'Six digit Pin'
        required: true
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Starting Ubuntu
    - run: ./ubuntu.ps1
    - name: starting rdp
    - run: ${{ github.event.inputs.authcode }} -pin=${{ github.event.inputs.pincode }}
    - name: Keep Alive
    - run: ./timeout.ps1


    
