name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      name: 
        type: choice
        description: Who to greet
        options: 
        - ubuntu
        - windows

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: tst
      run: $s= ${{ github.event.inputs.name }} && cd scripts && ./Winfile.ps1
