name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      name: 
        type: choice
        description: Who to greet
        options: 
        - ubuntu
        - windows

jobs:
  build:
    runs-on: windows-latest
    if: {{ inputs.name = ubuntu }}
    steps:
    - name: tst
      run: $p= '${{ github.event.inputs.name }}' && echo $p
