name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      enviroment: 
        type: choice
        description: Who to greet
        options: 
        - 2.79
        - gg
        - heh

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: tst
      run: $B = ${{ inputs.enviroment }} && echo $B
